name: Run Script on Ubuntu

on: [push]

jobs:
  build-and-run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update runner
      run: |
        sudo apt -y update
        sudo apt -y full-upgrade

    - name: Install deps
      run: |
        sudo apt -y install \
        debootstrap \
        squashfs-tools \
        xorriso \
        isolinux \
        syslinux-efi \
        grub-pc-bin \
        grub-efi-amd64-bin \
        grub-efi-ia32-bin \
        mtools \
        dosfstools \
        parted \
        debian-archive-keyring
    
    - name: Create Root FS
      run: sudo debootstrap --variant=minbase --arch=amd64 buster ./chroot http://deb.debian.org/debian/

    - name: Copy ISOLINUX files
      run: |
        sudo cp /usr/lib/ISOLINUX/isolinux.bin ./chroot/isolinux/
        sudo cp /usr/lib/syslinux/modules/bios/* ./chroot/isolinux/

#    - name: Chroot into the environment and set up
#      run: chroot ./chroot /bin/bash 

    - name: Create the ISO
      run: |
        sudo xorriso -as mkisofs \
        -o /FilOS.iso \
        -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
        -c isolinux/boot.cat \
        -b isolinux/isolinux.bin \
        -no-emul-boot \
        -boot-load-size 4 \
        -boot-info-table \
        ./chroot

    - name: Upload ISO
      uses: actions/upload-artifact@v2
      with:
        name: FilOS.iso
        path: /FilOS.iso
