name: Run Script on Ubuntu

on: [push]

jobs:
  build-and-run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update runner
      run: |
        sudo apt -y update
        sudo apt -y full-upgrade

    - name: Install deps
      run: sudo apt -y install debootstrap curl
    
    - name: Create Root FS
      run: sudo debootstrap --variant=minbase --arch=amd64 buster ./chroot http://deb.debian.org/debian/

    - name: Run Script
      run: bash /workspace/make-image.sh
