name: Run Script on Debian

on: [push]

jobs:
  build-and-run-script:
    runs-on: ubuntu-latest  # This uses the latest Ubuntu runner, which is a Debian-based system

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies (If needed)
      run: |
        sudo apt-get update
        sudo apt-get install -y YOUR_DEPENDENCY

    - name: Run Script
      run: |
        chmod +x ./path/to/your-script.sh
        ./path/to/your-script.sh
